eureka:
  client:
    registerWithEureka: true 
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
      - id: webportal-server
        uri: http://localhost:8080/
        predicates:
        - Path=/esign/webportal/**
       
        
#      - id: first-server
#        uri: http://localhost:8081/
#        predicates:
#        - Path=/esign/**
#        
#      - id: first-server
#        uri: http://localhost:8082/
#        predicates:
#        - Path=/consumer/**